services:
  db:
    image: postgres:17
    container_name: ecommerce_db_prod
    restart: always
    env_file:
      - .env.prod
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      retries: 5
      start_period: 30s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_web_prod
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod
    environment:
      DJANGO_ENV: prod
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"

volumes:
  postgres_data:
