# Generated by Django 5.2.1 on 2025-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='temp_username', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
