# Generated by Django 5.2.1 on 2025-07-08 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Flat or House No., Building, Apartment')),
                ('address_line2', models.CharField(max_length=255, verbose_name='Area, Street, Sector, Village')),
                ('landmark', models.CharField(blank=True, max_length=255, verbose_name='Landmark (Optional)')),
                ('city', models.CharField(default='Pune', max_length=100, verbose_name='Town or City')),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('pincode', models.CharField(max_length=6, verbose_name='Pincode')),
                ('use_for_home_service', models.BooleanField(default=True, verbose_name='Use this address for home delivery or service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
            },
        ),
    ]
