# Generated by Django 5.2.1 on 2025-06-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='home_delivery_address',
            field=models.TextField(blank=True, help_text='Address for home service, if applicable', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_home_service',
            field=models.BooleanField(default=False, help_text='Check if the customer requested home visit'),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_customers',
            field=models.PositiveIntegerField(default=1, help_text='Number of people for the booking (max 5)'),
        ),
    ]
