# Generated by Django 5.2.1 on 2025-07-09 19:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_home_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='home_visit_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('250.00'), help_text='Fee for home service visit. Applied only if is_home_service is True.', max_digits=8),
        ),
    ]
