# Generated by Django 5.2.1 on 2025-07-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_price_at_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='was_restocked',
            field=models.BooleanField(default=False),
        ),
    ]
