# Generated by Django 5.2.1 on 2025-07-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cancelled_by_customer_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='state',
        ),
    ]
