# Generated by Django 5.2.1 on 2025-07-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lto_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Limited Time Offer (LTO) % discount (active only during period)', max_digits=5),
        ),
    ]
