# Generated by Django 5.2.1 on 2025-07-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_lto_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
