# Generated by Django 5.2.1 on 2025-07-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_reserved_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='reserved_quantity',
        ),
    ]
